spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: #
    username: #
    password: #
    initialization-mode: always
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

